debug = true

logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      # CUSTOM CERTIFICATES
      [[entryPoints.https.tls.certificates]]
      certFile = "/certs/example.crt"
      keyFile = "/certs/example.key"
      # ... if you need more than one
      # [[entryPoints.https.tls.certificates]]
      # certFile = "/certs/traefik2.crt"
      # keyFile = "/certs/traefik2.key"
  [entryPoints.traefik]
  address = ":8080"

[retry]

[api]
entryPoint = "traefik"
dashboard = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "{{ .TRAEFIK_DOMAIN }}"
watch = true
exposedByDefault = false
swarmMode = true

# ACME / Let's Encrypt for all domains not in the certificates
[acme]
email = "{{ .CUSTOMER_EMAIL }}"
storage = "/mnt/acme/acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
